root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./apps/api/cmd/server"
bin = "./tmp/main"
delay = 3000

include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
exclude_regex = ["_test.go"]

[log]
time = true